name: Terraform-Apply-Pipeline

trigger:
  batch: true
  branches:
    include:
      - main
pool:
  vmImage: ubuntu-latest

variables:
  - template: variables.yaml

stages:
  - template: ../templates/stages/terraform-init-plan-stage-template.yml
    parameters: ${{ variables }}

  - template: ../templates/stages/terraform-apply-stage-template.yml
    parameters: ${{ variables }}

